# Basic Information 
title: Hyeonho Jeong
position: Research Engineer @ Adobe
affiliation: Adobe Research
email: hyeonhoj (at) adobe (dot) com

# Search Engine Optimization (SEO)
keywords: Hyeonho Jeong, video generation, video editing, diffusion models, Adobe Research, computer vision
description: Hyeonho Jeong is a Research Engineer at Adobe Research, working on video generation and editing with diffusion models.
canonical: https://hyeonho99.github.io/

# Links 
google_scholar: https://scholar.google.com/citations?user=Pa7EfsEAAAAJ
cv_link: assets/files/resume.pdf
github_link: https://github.com/hyeonho99
linkedin: https://www.linkedin.com/in/hyeonho-jeong-jhh/
twitter: https://twitter.com/Hyeonho_Jeong99

# Images
avatar: ./assets/img/malaga.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Sans Serif"

# Google Analytics ID
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
